import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :oas, Oas.Repo,
  database: System.get_env("DB_FILE") || "/dbs/sqlite-prod.db",
  backup_database: "/dbs-backup/sqlite-backup"

config :oas, Oas.Repo.Replica1,
  database: System.get_env("DB_FILE_REPLICA_1") || "/dbs-replica-1/sqlite-prod-replica-1.db"

# Do not print debug messages in production
config :logger, level: :info

config :oas, OasWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  url: [
    host: "server.oxfordshireacrosociety.co.uk",
    port: 443,
    scheme: "https"
  ],
  domain: System.get_env("DOMAIN") || ".oxfordshireacrosociety.co.uk",
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "HAADR1Os6bgYyXaQAdK6Jf8R8VgDX6wtWpa3py2lJNtuKEsizYYiLj3uJR6QTSoN",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

config :oas, Oas.Mailer, adapter: Swoosh.Adapters.SMTP,
  relay: "smtp.gmail.com",
  username: "chrisjbishop155",
  port: 587,
  password: "wmtlwjekfjcrksrf",
  auth: :always

config :oas, Oas.TokenMailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "smtp.gmail.com",
  username: "chrisjbishop155",
  port: 587,
  password: "wmtlwjekfjcrksrf",
  auth: :always

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :oas, OasWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :oas, OasWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

config :phoenix, :stacktrace_depth, 20

config :phoenix, :plug_init_mode, :runtime

config :oas,
  app_url: System.get_env("REACT_APP_ADMIN_URL") || "https://admin.oxfordshireacrosociety.co.uk",
  public_url: System.get_env("REACT_APP_PUBLIC_URL") || "https://www.oxfordshireacrosociety.co.uk"
